### ISSUE TITLE
How to create Header and Footer?

### ISSUE THREAD

**Issue by bikramchettri** [gamalielmendez/node-fpdf#10]
How to create headers and footers can you provide examples?
How to print the page number for each page?
Can you provide details?

**Comment by erikn69** [comment]
http://www.fpdf.org/en/tutorial/index.php
http://www.fpdf.org/

On fpdf you can find all the documentation, and examples, download the original version

**Comment by bikramchettri** [comment]
This is the code.
https://replit.com/@bikramchettri/pdf-creator#index.js
I tried I wanted to know how to use AliasNbPages.

**Comment by angeljqv** [comment]
http://www.fpdf.org/en/doc/aliasnbpages.htm

`pdf1.AliasNbPages();` ??

**Comment by gamalielmendez** [comment]
I fixed the conflict in the call to the AliasNbPages() method by renaming the AliasNbPages variable to AliasNbPages_.
now it works correctly

**Comment by bikramchettri** [comment]
It works now!
