### ISSUE TITLE
Actual FPDF version is `1.85`

### ISSUE THREAD

**Issue by parallels999** [gamalielmendez/node-fpdf#11]
https://github.com/gamalielmendez/node-fpdf/blob/d486d629d857536ecc0c2abd5c05572695a513aa/src/fpdf_js.js#L28

Actual FPDF version is `1.85`, does that affect this library in any way?

**Comment by gamalielmendez** [comment]
not really, it is only used in the metadata to show the version of the library.

**Comment by parallels999** [comment]
Thanks for answer
