### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [gamalielmendez/node-fpdf#17]
Greetings,
Does this lovely package supports working in Browser? If not, what it would take to make it so? 

Thank you!

**Comment by gamalielmendez** [comment]
Unfortunately, node-fpdf is not compatible with the browser, as it relies on specific Node.js API libraries, such as stream and fs, which are not available in the browser environment. To make it work in a browser environment, it would be necessary to seek alternatives to these libraries or rewrite certain parts of the code to adapt it to the browser context.
