### ISSUE TITLE
Image() does not work as expected

### ISSUE THREAD

**Issue by stoeff42** [gamalielmendez/node-fpdf#20]
I am trying to use Image() to include an image in my PDF.
Whatever I try, I am not able to. Instead of the image, I only get a black rectangle where the image is supposed to be in the PDF.
No error message appears and the PDF is otherwise created as expected.
I have tried different images in different formats, and I always get this same result.
I have tried with both nodejs v18.12.1 and v20.15.0.
Please find below a minimal example. Corresponding image file and resulting PDF is attached.

const Fpdf = require('node-fpdf')
const fs = require('fs')

let pdf = new Fpdf();
pdf.SetCompression(false);

pdf.AddPage();
pdf.Image(`a.jpg`);

let data = pdf.Output('s');
fs.writeFileSync('test.pdf', data);

![a](https://github.com/gamalielmendez/node-fpdf/assets/871611/c8d83d78-4094-4659-bced-874c6af4601b)
[test.pdf](https://github.com/user-attachments/files/15956246/test.pdf)

**Comment by gamalielmendez** [comment]
Hello, please check the path of your image.
[testImageReport.pdf](https://github.com/user-attachments/files/16090073/testImageReport.pdf)

**Comment by gamalielmendez** [comment]
Check the test folder; there is an example of how to load an image there.
